apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-postgres
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Capten
        type: postgres
        url: {{ .Values.datasources.postgreSQL.url }}
        user: postgres
        secureJsonData:
        password: "$POSTGRESQL_PASSWORD"
        jsonData:
        database: capten
        sslmode: 'disable' # disable/require/verify-ca/verify-full

    - name: Proact
        type: postgres
        url: {{ .Values.datasources.postgreSQL.url }}
        user: postgres
        secureJsonData:
        password: "$POSTGRESQL_PASSWORD"
        jsonData:
        database: scsctl
        sslmode: 'disable' # disable/require/verify-ca/verify-full    

    - name: QualityTrace
        type: postgres
        url: {{ .Values.datasources.postgreSQL.url }}
        user: postgres
        secureJsonData:
        password: "$POSTGRESQL_PASSWORD"
        jsonData:
        database: qualitytrace
        sslmode: 'disable' # disable/require/verify-ca/verify-full    